INSERT INTO PILLAR.MAIN.stories (headline, event_date, status, enrichments)
SELECT column1, CURRENT_TIMESTAMP(), 'raw', PARSE_JSON(column2)
FROM VALUES
('Live Updates: Iran says it "cannot trust the Americans at all" as Trump says "we control" the Strait of Hormuz - CBS News', $${"outlet_id": 301, "url": "https://www.cbsnews.com/live-updates/iran-war-trump-strait-of-hormuz-trust-americans-control/", "summary": "Speaking to reporters on Air Force One, President Trump also claimed to have \"wiped out\" Iran's armed forces."}$$),
('Tennnessee Democrat Steve Cohen announces retirement - Politico', $${"outlet_id": 302, "url": "https://www.politico.com/live-updates/2026/05/15/congress/steve-cohen-tennessee-retire-00923361", "summary": "Cohen's Memphis-based district was recently dismantled in a Republican gerrymandering effort."}$$),
('Stock Market Today: Dow Falls 400 Points Lower on Oil Price Fears — Live Updates - WSJ', $${"outlet_id": 303, "url": "https://www.wsj.com/livecoverage/stock-market-today-dow-sp-500-nasdaq-05-15-2026", "summary": ""}$$),
('DOJ pushing to indict Raúl Castro over 1996 downing of civilian planes, officials say - NBC News', $${"outlet_id": 304, "url": "https://www.nbcnews.com/politics/justice-department/doj-pushing-indict-raul-castro-1996-downing-civilian-planes-officials-rcna345296", "summary": "The Justice Department is pushing to indict 94-year-old Raúl Castro, the former president of Cuba, according to two U.S. officials familiar with the matter."}$$),
('Good Night and Good Luck, Motherf-kers: Letterman and Colbert Toss CBS Property Off the Roof - Rolling Stone', $${"outlet_id": 305, "url": "http://www.rollingstone.com/tv-movies/tv-movie-news/colbert-letterman-cbs-property-off-roof-1235563362/", "summary": "As we inch closer to the final date of The Late Show With Stephen Colbert, the host and David Letterman toss CBS property off the roof."}$$),
('In pageantry and politics, China summit yields Xi''s goal — equal footing with U.S. - The Washington Post', $${"outlet_id": 306, "url": "https://www.washingtonpost.com/politics/2026/05/15/beijing-summit-yields-chinese-goal-equal-footing-with-us/", "summary": "The image of peer superpowers during President Trump's visit displayed a dynamic that analysts say the Chinese have long sought and Americans had resisted."}$$);
