/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsKeyRouteImport } from './routes/api/tts-key'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiPanelScriptRouteImport } from './routes/api/panel-script'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsKeyRoute = ApiTtsKeyRouteImport.update({
  id: '/api/tts-key',
  path: '/api/tts-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanelScriptRoute = ApiPanelScriptRouteImport.update({
  id: '/api/panel-script',
  path: '/api/panel-script',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/panel-script': typeof ApiPanelScriptRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-key': typeof ApiTtsKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/panel-script': typeof ApiPanelScriptRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-key': typeof ApiTtsKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/panel-script': typeof ApiPanelScriptRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-key': typeof ApiTtsKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/panel-script' | '/api/tts' | '/api/tts-key'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/panel-script' | '/api/tts' | '/api/tts-key'
  id: '__root__' | '/' | '/api/panel-script' | '/api/tts' | '/api/tts-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPanelScriptRoute: typeof ApiPanelScriptRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiTtsKeyRoute: typeof ApiTtsKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-key': {
      id: '/api/tts-key'
      path: '/api/tts-key'
      fullPath: '/api/tts-key'
      preLoaderRoute: typeof ApiTtsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panel-script': {
      id: '/api/panel-script'
      path: '/api/panel-script'
      fullPath: '/api/panel-script'
      preLoaderRoute: typeof ApiPanelScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPanelScriptRoute: ApiPanelScriptRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiTtsKeyRoute: ApiTtsKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
